package org.subham.merjency.dataaccess;

public enum DataAccessMethodResponse {
	INVALID_RESOURCE_INSERTION,
	INVALID_RESOURCE_MODIFICATION,
	INVALID_RESOURCE_DELETION,
	VALID_RESOURCE_INSERTION,
	VALID_RESOURCE_MODIFICATION,
	VALID_RESOURCE_DELETION
}
